baseURL = 'https://freshlymarried.com'
languageCode = 'en-us'
title = 'Freshly Married'
theme = "ananke"
paginate = 20
googleAnalytics = "UA-46767990-1"
enableRobotsTXT = true

[permalinks]
  posts = '/:filename/'

[menu]

[[menu.main]]
  identifier = 'recent'
  name = 'Recent'
  title = 'Recent'
  url = '/'
  weight = 1

[[menu.main]]
  identifier = 'posts'
  name = 'Posts'
  title = 'Posts'
  url = '/posts/'
  weight = 2

[[menu.main]]
  identifier = 'about'
  name = 'About'
  title = 'About'
  url = '/about/'
  weight = 3

[[menu.main]]
  identifier = 'newsletter'
  name = 'Newsletter'
  title = 'Newsletter'
  url = 'https://mailchi.mp/bd78e63417c4/freshly-married-newsletter'
  weight = 4

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  author = "Amy Miller"
  favicon = "/images/favicon.png"
  site_logo = "/images/logo.png"
  description = "Keepin' marriage fresh"
  recent_posts_number = 20
  body_classes = "avenir bg-near-white mw9 center"
  post_content_classes = "avenir"
  disclaimer = "This site does not provide medical or mental health counseling advice, diagnosis or treatment. Freshly Married is a for-profit website, meaning that it may contain paid advertisements, sponsored posts and giveaways, and affiliate links. Sponsored content will be labeled as such. The products and companies that I share are ones that can somehow benefit your family relationships, as that’s what Freshly Married’s mission is. Opinions are my own. Freshly Married is a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for sites to earn advertising fees by advertising and linking to amazon.com."

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/freshlymarriedadventures/"

[[params.ananke_socials]]
name = "instagram"
url = "https://instagram.com/freshlymarried"
